# Generated by Django 3.0.8 on 2020-08-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200824_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='surname',
        ),
    ]
